export default Object.freeze({
  WELCOME: 'WELCOME_SCREEN',
  LOGIN: 'LOGIN_SCREEN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  SUBMIT_FORGOT_PASSWORD: 'SUBMIT_FORGOT_PASSWORD',
  DASHBOARD: 'DASHBOARD',
  AUTH: 'AUTH',
});
